### ISSUE TITLE
ETL() calculation details and documentation

### ISSUE THREAD

**Issue by wwyws0000** [braverock/PerformanceAnalytics#119]
Hi,

The documentation for the ETL() function is missing the Detail section, which I believe is critical to understand a lot of the nuances in this implementation (for example, the "operational" parameter).

Another issue ( I could be wrong about this) is some misleading explanation of parameters. For example, m3 and m4 are being told as skewness/coskewness and kurtosis/cokurtosis of the series in the documentation. However, when reviewing the code as well as the referenced paper, m3 and m4 is actually the 3rd and 4th central moment. 

Could you please look into these issues and let me know if I was correct about m3 and m4? Really appreciate the functionalities of this package, looking forward to the response.

Thanks,

**Comment by braverock** [comment]
if univariate, m3/m4 are the third and fourth central moments.  That is skewness and kurtosis.  So I think you are being unclear or don't understand?

m3 and m4, if matrices, are the co-matrices for the third (skewness) and fourth (kurtosis) moments of the distribution. 

So I guess maybe we can improve the documentation, but I'm trying to understand what you think the difference is?

**Comment by wwyws0000** [comment]
I can be wrong but aren't skewness and kurtosis the **standardized** moments as opposed to central moments? Standardized moments will need to be normalized , typically through division of some expression of standard deviation

**Comment by wwyws0000** [comment]
![image](https://user-images.githubusercontent.com/38261044/57039247-2368ae80-6c2a-11e9-8f19-2fa65a3f1ff3.png)

this is the direct excerpt from the referenced paper in the documentation.

**Comment by wwyws0000** [comment]
Any comment?

**Comment by wwyws0000** [comment]
Please provide an explanation.

**Comment by braverock** [comment]
What is unclear about the explanation in the paper?  The code in PerformanceAnalytics was used for that and multiple other papers, and I believe that it matches precisely.  What is the gap in your understanding?

If *univariate*. you pass the skewness and kurtosis.  if *matrices*, you pass the M3 and M4 matrices, as I've already described.

**Comment by wwyws0000** [comment]
If you actually bothered to read what I've wrote, maybe this conversation doesn't need to be this difficult?

Yes, the documentation says that if univariate, you pass in m3 as the skewness. BUT, what the code does, when m3 is not passed in, is to calculate m3 as the 3rd central moment, which is NOT the same as standard definition of skewness. This means, either that there's a mistake in the code, or there's a mistake in the documentation. 

> if univariate, m3/m4 are the third and fourth central moments. That is skewness and kurtosis. So I think you are being unclear or don't understand?


Again, m3/m4, the 3rd and 4th centralized moments, are NOT the same as skewness and kurtosis.

**Comment by braverock** [comment]
The code is fine.
So is the documentation.  
m3 and m4 are *multivariate matrices* in the multivariate input case, as clearly stated.  If you tried to pass a univariate skewness or kurtosis, or a vector of skewnesses, or something, it will (obviously) fail in the multivariate case.
as I said two weeks ago, if you would like to propose a patch to the documentation to make it more clear for you and others to understand, then please do so.
