### ISSUE TITLE
The portfolio.spec(.) function is not available

### ISSUE THREAD

**Issue by QuantDevHacks** [braverock/PerformanceAnalytics#143]
I hope I'm not missing something obvious here, but in attempting to present the basic minimum variance optimization problem to my undergraduate *R in Quant Finance* course, I tried to use the example outlined in the portfolio_vignette.pdf file on CRAN.

The solution seems center on the ```porfolio.spec(.)``` function; however, when I attempt to use it, there is an error from PerformanceAnalytics saying this function doesn't exist.  It also is not present in the help file that accompanies the package.

Is this in fact the case?  If so, would you have any updated documentation available to solve this admittedly very basic problem using PortfolioAnalytics?  I've tried searching further, but so far to no avail.  For now, I'm using ```solve.QP(.)``` in the quadprog package, but it would be nice if we could use something similar to that described in the vignette.

Thanks in advance.

**Comment by braverock** [comment]
That function, and that vignette, is in `PortfolioAnalytics`, not `PerformanceAnalytics`

https://cran.r-project.org/web/packages/PortfolioAnalytics/index.html

Closing this ticket, since I think this will resolve things.

**Comment by QuantDevHacks** [comment]
D'OH!!!  Sorry about that, and thanks very much.
