### ISSUE TITLE
DESCRIPTION error

### ISSUE THREAD

**Issue by evelynmitchell** [braverock/PerformanceAnalytics#55]
R CMD check PerformanceAnalytics 
* using log directory ‘<mylocadir>plotxtsTesting/perfA/PerformanceAnalytics.Rcheck’
* using R version 3.3.1 (2016-06-21)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘PerformanceAnalytics/DESCRIPTION’ ... ERROR
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
* DONE

Status: 1 ERROR

I took a look at the DESCRIPTION file, and I can't see why this throwing an error. There is both an 'aut' and a 'cre' role, which should build to both Author and Maintainer. The suggested usage doesn't include 'first=' or 'family=', but also doesn't preclude their use, and specifically mentions allowing them only when they have single values, which is not the case for this package, where one of the people has an initial.

This shows up on R CMD check PerformanceAnalytics. The package builds cleanly after installing 'gplots' and 'Hmisc'.

**Comment by joshuaulrich** [comment]
You used to be able to run `R CMD check` on the package source, but that apparently (no longer?) plays well with the `Authors@` usage.  So you should run `R CMD check` on the tarball created by `R CMD build`, which parses the `Authors@` field into valid `DESCRIPTION` fields.

**Comment by evelynmitchell** [comment]
If I do  R CMD build PerformanceAnalytics, then extract the tar.gz to a clean directory,  the DESCRIPTION error doesn't occur
diff <source> <build>

diff PerformanceAnalytics/DESCRIPTION ../PerformanceAnalytics/DESCRIPTION 
26,39c26,29
< Imports:
<     zoo
< Depends:
<     R (>= 3.0.0),
<     xts (>= 0.10.0)
< Suggests:
<     Hmisc,
<     MASS,
<     quantmod,
<     gamlss,
<     gamlss.dist,
<     robustbase,
<     quantreg,
<     gplots
---
> Imports: zoo
> Depends: R (>= 3.0.0), xts (>= 0.10.0)
> Suggests: Hmisc, MASS, quantmod, gamlss, gamlss.dist, robustbase,
>         quantreg, gplots
43a34,45
> NeedsCompilation: yes
> Packaged: 2016-07-03 15:43:15 UTC; efm
> Author: Brian G. Peterson [cre, aut, cph],
>   Peter Carl [aut, cph],
>   Kris Boudt [ctb, cph],
>   Ross Bennett [ctb],
>   Joshua Ulrich [ctb],
>   Eric Zivot [ctb],
>   Matthieu Lestel [ctb],
>   Kyle Balkissoon [ctb],
>   Diethelm Wuertz [ctb]
> Maintainer: Brian G. Peterson <brian@braverock.com>

**Comment by joshuaulrich** [comment]
Sorry if I wasn't clear, but the "error" is somewhat expected due to how `R CMD check` works with packages that use the `Authors@R` field.  And the fix is to run `R CMD check` on the tarball created by `R CMD build`.
