### ISSUE TITLE
warnings on char.Correlation() output.

### ISSUE THREAD

**Issue by sdroldan** [braverock/PerformanceAnalytics#62]
When I run the char.Correlation function, this give some warnings about "method" as graphical parameter. 

> Warning in plot.window(...): "method" is not a graphical parameter
> Warning in plot.xy(xy, type, ...): "method" is not a graphical parameter
>  Warning in title(...): "method" is not a graphical parameter
>  Warning in plot.window(...): "method" is not a graphical parameter
>  Warning in plot.xy(xy, type, ...): "method" is not a graphical parameter
>  Warning in title(...): "method" is not a graphical parameter
>  Warning in axis(side = side, at = at, labels = labels, ...): "method" is
>  not a graphical parameter 

```
 mydata <- mtcars[, c(1,3,4,5,6,7)]
 head(mydata)
```

> mpg disp hp drat wt qsec
> Mazda RX4 21.0 160 110 3.90 2.620 16.46
> Mazda RX4 Wag 21.0 160 110 3.90 2.875 17.02
> Datsun 710 22.8 108 93 3.85 2.320 18.61
> Hornet 4 Drive 21.4 258 110 3.08 3.215 19.44
> Hornet Sportabout 18.7 360 175 3.15 3.440 17.02
> Valiant 18.1 225 105 2.76 3.460 20.22  

```
library(PerformanceAnalytics)
```

> Loading required package: xts
> Loading required package: zoo
> 
> Attaching package: ‘zoo’
> 
> The following objects are masked from ‘package:base’:
> 
> as.Date, as.Date.numeric
> 
> Package PerformanceAnalytics (1.4.3541) loaded.
> Copyright (c) 2004-2014 Peter Carl and Brian G. Peterson, GPL-2 | GPL-3
> http://r-forge.r-project.org/projects/returnanalytics/
> 
> Attaching package: ‘PerformanceAnalytics’
> 
> The following object is masked from ‘package:graphics’:
> 
> legend  

```
chart.Correlation(mydata, histogram=TRUE, pch=19)
```

> There were 50 or more warnings (use warnings() to see the first 50)  

```
 warnings()
```

> Warning messages:
> 1: "method" is not a graphical parameter
> 2: "method" is not a graphical parameter
> ....
> 50: "method" is not a graphical parameter  

(by  www.sthda.com's administrator Kassambara,thank's to he) .
The trouble is in the last line of the chart.Correlation() code, whith use of parameter "method" as an argument of the plotting function pair(), which, doesn't take "method" as an argument."

**Comment by Teebusch** [comment]
As a workaround you can wrap your code in `suppressWarnings()`, like this
`suppressWarnings(chart.Correlation(mydata, histogram=TRUE, pch=19))`

**Comment by braverock** [comment]
this is fixed in current code
