### ISSUE TITLE
Missing lag when using monthly data in Return.portfolio

### ISSUE THREAD

**Issue by Aylon1** [braverock/PerformanceAnalytics#71]
Return.portfolio providing monthly (end of month) returns and an (end of month) weights xts, returns the result at an incorrect index date. 

The asset return [on 2009-12-31] is in the result sets forwarded and in the portfolio return showing as November [2009-11-30] return. 

It is clear from the docs (and common sense), that the weights in the weights xts are applied to the following period. 

However, in the routine are the returns shifted one period forward instead of the weights being shifted to the next period. 

Its also clear where this happens and from the code is Return.portfolio working as written. Nonetheless can I not see how this is intended as it seems clashing with reality?

Thorsten

Reproducible example below:
```
library(PerformanceAnalytics)

# date index
ind <-
  as.Date(
    c(
      "2009-05-29",
      "2009-06-30",
      "2009-07-31",
      "2009-08-31",
      "2009-09-30",
      "2009-10-30",
      "2009-11-30",
      "2009-12-31",
      "2010-01-29",
      "2010-02-26",
      "2010-03-31",
      "2010-04-30",
      "2010-05-28",
      "2010-06-30",
      "2010-07-30",
      "2010-08-31",
      "2010-09-30",
      "2010-10-29",
      "2010-11-30",
      "2010-12-31",
      "2011-01-31",
      "2011-02-28",
      "2011-03-31",
      "2011-04-29"
    )
  )

# returns
SPXL <-
  c(
    0,
    -0.00676083145332229,
    0.201537816365289,
    0.0890067047243612,
    0.0837519562504003,
    -0.0923428062112165,
    0.152566413542857,
    0.109043490255932,
    -0.0888696341774087,
    0.119382564497689,
    0.207849194317418,
    0.0616100654682032,
    -0.200532215846242,
    -0.185894020718424,
    0.13266359454862,
    -0.114465233830422,
    0.178396948109459,
    0.0944718715149588,
    0.0639950206444209,
    0.166177181239701,
    0.0389874686626885,
    0.0885652786314444,
    -0.029462615512327,
    0.0387294526468933
  )
MIDU <-
  c(
    0,
    -0.0157373031989327,
    0.235173846067467,
    0.118400003420994,
    0.130683240655227,
    -0.163938646550673,
    0.117041293596222,
    0.198389750428653,
    -0.0807477054269103,
    0.156494869036318,
    0.287030520244803,
    0.122206981534812,
    -0.192485125773042,
    -0.206024661270754,
    0.133128380723946,
    -0.122325138663754,
    0.220021722426928,
    0.0903396491300028,
    0.113617603795667,
    0.169469079535749,
    0.0288200457281305,
    0.0936284787545618,
    0.0119208972425999,
    0.0392601972133422
  )
CASH <- c(rep(0, length(MIDU)))

# weights
wSPXL <- c(0, 0, 0, 0, 0, 0, 1, 1, 0.5, 0, 0, 0.5, 0, 0, 0, 0, 0.5, 1, 1, 1, 1, 1, 1, 1)
wMIDU <- c(0, 0, 0, 0, 0, 0, 0, 0, 0.5, 1, 1, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
wCASH <- c(1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0)

R <-
  xts(
    data.frame(SPXL = SPXL, MIDU = MIDU, CASH = CASH),
    order.by = ind,
    dateFormat = "Date"
  )
weights <-
  xts(
    data.frame(SPXL = wSPXL, MIDU = wMIDU, CASH = wCASH),
    order.by = ind,
    dateFormat = "Date"
  )

# clean up
rm(SPXL, MIDU, CASH, wSPXL, wMIDU, wCASH, ind)

portfolio.return <-
  Return.portfolio(R = R,
                   weights = weights,
                   verbose = T)

# clarify colnames
colnames(R) <- paste0("R.", colnames(R))
contribution <- portfolio.return$contribution
colnames(contribution) <- paste0("Cont.", colnames(contribution))
colnames(weights) <- paste0("W.", colnames(weights))

# combine excl CASH as not adding value to visualize question
head(cbind(contribution[, -3], R[, -3], weights[, -3]), 12)


```

Results in the below whereas it is impossible to achieve in November the monthly return from 01.12.-31.12.:

| Date | Cont.SPXL | Cont.MIDU | R.SPXL | R.MIDU | W.SPXL | W.MIDU |
| -------------| -------------| -------------| -------------| -------------| -------------| -------------|
| 2009-05-29 | 0.00000000 | 0.00000000 | 0.000000000 | 0.00000000 | 0.0 | 0.0 |
| 2009-06-30 | 0.00000000 | 0.00000000 | -0.006760831 | -0.01573730 | 0.0 | 0.0 |
| 2009-07-31 | 0.00000000 | 0.00000000 | 0.| 201537816 | 0.23517385 | 0.0 | 0.0 |
| 2009-08-31 | 0.00000000 | 0.00000000 | 0.089006705 | 0.11840000 | 0.0 | 0.0 |
| 2009-09-30 | 0.00000000 | 0.00000000 | 0.083751956 | 0.13068324 | 0.0 | 0.0 |
| 2009-10-30 | 0.00000000 | 0.00000000 | -0.092342806 | -0.16393865 | 0.0 | 0.0 |
| 2009-11-30 | **0.10904349** | 0.00000000 | 0.152566414 | 0.11704129 | 1.0 | 0.0 |
| 2009-12-31 | **-0.08886963** | 0.00000000 | **0.109043490** | 0.19838975 | 1.0 | 0.0 |
| 2010-01-29 | **0.05969128** | **0.07824743** | **-0.088869634** | -0.08074771 | 0.5 | 0.5 |
| 2010-02-26 | 0.00000000 | 0.28703052 | **0.119382564** | **0.15649487** | 0.0 | 1.0 |
| 2010-03-31 | 0.00000000 | 0.12220698 | 0.207849194 | 0.28703052 | 0.0 | 1.0 |
| 2010-04-30 | -0.10026611 | -0.09624256 | 0.061610065 | 0.12220698 | 0.5 | 0.5 |

As mentioned in the docs, are the weights applied to the following period but my expectation would hence be:

```
# expected result
portfolio.return.2 <-
  R * lag.xts(weights) # or alternatively lag all output from Return.portfolio

head(cbind(portfolio.return.2[, -3], R[, -3], lag.xts(weights)[, -3]), 12)
```

As result:

| Date | R.SPXL | R.MIDU | R.SPXL.1 | R.MIDU.1 | W.SPXL | W.MIDU |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------ |
| 2009-05-29 | NA | NA | 0.000000000 | 0.00000000 | NA | NA |
| 2009-06-30 | 0.00000000 | 0.00000000 | -0.006760831 | -0.01573730 | 0.0 | 0.0 |
| 2009-07-31 | 0.00000000 | 0.00000000 | 0.201537816 | 0.23517385 | 0.0 | 0.0 |
| 2009-08-31 | 0.00000000 | 0.00000000 | 0.089006705 | 0.11840000 | 0.0 | 0.0 |
| 2009-09-30 | 0.00000000 | 0.00000000 | 0.083751956 | 0.13068324 | 0.0 | 0.0 |
| 2009-10-30 | 0.00000000 | 0.00000000 | -0.092342806 | -0.16393865 | 0.0 | 0.0 |
| 2009-11-30 | 0.00000000 | 0.00000000 | 0.152566414 | 0.11704129 | 0.0 | 0.0 |
| 2009-12-31 | **0.10904349** | 0.00000000 | **0.109043490** | 0.19838975 | 1.0 | 0.0 |
| 2010-01-29 | -0.08886963 | 0.00000000 | -0.088869634 | -0.08074771 | 1.0 | 0.0 |
| 2010-02-26 | 0.05969128 | 0.07824743 | 0.119382564 | 0.15649487 | 0.5 | 0.5 |
| 2010-03-31 | 0.00000000 | 0.28703052 | 0.207849194 | 0.28703052 | 0.0 | 1.0 |
| 2010-04-30 | 0.00000000 | 0.12220698 | 0.061610065 | 0.12220698 | 0.0 | 1.0 |

Session Info:
```
sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] PerformanceAnalytics_1.4.3541 xts_0.9-7                     zoo_1.8-0                    

loaded via a namespace (and not attached):
[1] tools_3.2.3     grid_3.2.3      lattice_0.20-33

```

**Comment by braverock** [comment]
This problem does not exist in current PerformanceAnalytics.

    head(cbind(contribution[, -3], R[, -3], weights[, -3]), 12) 

| Date |Cont.SPXL |Cont.MIDU |R.SPXL |R.MIDU |W.SPXL |W.MIDU |
| -------------| -----------| -----------| -----------| -----------| -----------| -----------|
|2009-05-29 |NA |NA |0.000000000 |0.00000000 |0.0 |0.0 | 
|2009-06-30 |0.00000000 |0.00000000 |-0.006760831 |-0.01573730 |0.0 |0.0 |
|2009-07-31 |0.00000000 |0.00000000 |0.201537816 |0.23517385 |0.0 |0.0 |
|2009-08-31 |0.00000000 |0.00000000 |0.089006705 |0.11840000 |0.0 |0.0 |
|2009-09-30 |0.00000000 |0.00000000 |0.083751956 |0.13068324 |0.0 |0.0 |
|2009-10-30 |0.00000000 |0.00000000 |-0.092342806 |-0.16393865 |0.0 |0.0 |
|2009-11-30 |0.00000000 |0.00000000 |0.152566414 |0.11704129 |1.0 |0.0 |
|2009-12-31 |0.10904349 |0.00000000 |0.109043490 |0.19838975 |1.0 |0.0 |
|2010-01-29 |-0.08886963 |0.00000000 |-0.088869634 |-0.08074771 |0.5 |0.5 | 
|2010-02-26 |0.05969128 |0.07824743 |0.119382564 |0.15649487 |0.0 |1.0 |
|2010-03-31 |0.00000000 |0.28703052 |0.207849194 |0.28703052 |0.0 |1.0 |
|2010-04-30 |0.00000000 |0.12220698 |0.061610065 |0.12220698 |0.5 |0.5 |

I happen to be using *PerformanceAnalytics* 1.5.1 on this machine, but any recent version will not display this problem.

We'll push a new version of *PerformanceAnalytics* to CRAN sometime after the new *xts* goes to CRAN

**Comment by Aylon1** [comment]
Many thanks
