### ISSUE TITLE
Return.portfolio fails when called on xts object w/POSIXct index and rebalance_on specified

### ISSUE THREAD

**Issue by joshuaulrich** [braverock/PerformanceAnalytics#72]
Here's a reproducible example:

```r
library(PerformanceAnalytics)
data(edhec)
index(edhec) <- as.POSIXct(index(edhec))
rp <- Return.portfolio(edhec, rebalance_on = "months")
# Error in `[<-`(`*tmp*`, k, , value = end_value * weights[i, ]) : 
#   subscript out of bounds
```

The cause is [L184 in Return.portfolio.R](https://github.com/braverock/PerformanceAnalytics/blob/337f902f9e4ced6ddcca61612fc6523798da8fae/R/Return.portfolio.R#L184):

```r
weight_dates = c(as.Date(start_date), index(R[endpoints(R, on=rebalance_on)]))
```

That call to `c` causes the POSIXct index to be converted to Date in a very add manner... as if it's converting the underlying number of seconds to number of days.

```r
R> c(Sys.Date(), Sys.time())
[1] "2017-06-04"    "4099558-09-23"
```

The fix seems to be as simple as converting POSIXct vector to Date before calling `c`:

```r
R> c(Sys.Date(), as.Date(Sys.time()))
[1] "2017-06-04" "2017-06-04"
```

**Comment by Jmarks199** [comment]
I'm still having this same issue in version 1.4.3541?

**Comment by braverock** [comment]
@Jmarks199 , please reinstall from github.  This is not on CRAN yet.

**Comment by Jmarks199** [comment]
Thank you
