### ISSUE TITLE
bug in lpm

### ISSUE THREAD

**Issue by helix123** [braverock/PerformanceAnalytics#73]
There seems to be a bug in function `lpm`:
In the following line, the maximum function does not return a vector but a single value while it should compare each element of `R_avg-x_cond` with `0`. Thus, the sum of only one value is computed.
One would need some kind of vectorised version of `max`.
`LPM = (1/nb) * sum(max(0,R_avg-x_cond)^n)`

Take heed, if #64 is to be applied, as it also contains that line.

**Comment by braverock** [comment]
the lower partial moment is a point estimate, not a time series estimate.

by the time you get to max, the time series data has already been compressed to a single number.

What are you proposing?

**Comment by helix123** [comment]
`R_avg-x_cond` is not compressed to a single number when taking max, it is still a vector with length > 1.
According to theory, don't we want to compare each element of that vector to 0 (take the max pairwise 0 vs. each element of  `R_avg-x_cond`)? (`R_avg` is a single number).

Btw: If  `R_avg-x_cond` was a single number, `sum()` wouldn't make sense?

**Comment by helix123** [comment]
Don't we want `sum((R_avg-x_cond)[R_avg-x_cond >= 0]^n)` there?

**Comment by helix123** [comment]
Or simply `sum(pmax(0,R_avg-x_cond)^n)` (with `pmax`, the parallel max function)

**Comment by helix123** [comment]
Another check would be to compare to Rmetrics function for lower partial moments.
